2024-02-06 16:01:49,840:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2024-02-06 16:01:49,840:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2024-02-06 16:01:49,840:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2024-02-06 16:01:49,840:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2024-02-06 16:44:16,569:INFO:PyCaret ClassificationExperiment
2024-02-06 16:44:16,569:INFO:Logging name: clf-default-name
2024-02-06 16:44:16,569:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2024-02-06 16:44:16,569:INFO:version 3.2.0
2024-02-06 16:44:16,569:INFO:Initializing setup()
2024-02-06 16:44:16,569:INFO:self.USI: 9edf
2024-02-06 16:44:16,569:INFO:self._variable_keys: {'idx', 'n_jobs_param', 'fix_imbalance', 'gpu_param', '_available_plots', 'y_test', 'fold_generator', 'pipeline', 'html_param', 'fold_shuffle_param', 'X', 'log_plots_param', 'fold_groups_param', 'X_train', '_ml_usecase', 'X_test', 'y', 'is_multiclass', 'exp_id', 'y_train', 'gpu_n_jobs_param', 'target_param', 'exp_name_log', 'data', 'memory', 'logging_param', 'seed', 'USI'}
2024-02-06 16:44:16,569:INFO:Checking environment
2024-02-06 16:44:16,569:INFO:python_version: 3.10.13
2024-02-06 16:44:16,569:INFO:python_build: ('main', 'Sep 11 2023 08:39:02')
2024-02-06 16:44:16,569:INFO:machine: x86_64
2024-02-06 16:44:16,570:INFO:platform: macOS-10.16-x86_64-i386-64bit
2024-02-06 16:44:16,570:INFO:Memory: svmem(total=17179869184, available=6803992576, percent=60.4, used=9204830208, free=143544320, active=6650933248, inactive=6324314112, wired=2553896960)
2024-02-06 16:44:16,570:INFO:Physical Core: 4
2024-02-06 16:44:16,570:INFO:Logical Core: 8
2024-02-06 16:44:16,570:INFO:Checking libraries
2024-02-06 16:44:16,571:INFO:System:
2024-02-06 16:44:16,571:INFO:    python: 3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ]
2024-02-06 16:44:16,571:INFO:executable: /Applications/anaconda3/envs/consta_ml/bin/python
2024-02-06 16:44:16,571:INFO:   machine: macOS-10.16-x86_64-i386-64bit
2024-02-06 16:44:16,571:INFO:PyCaret required dependencies:
2024-02-06 16:44:16,891:INFO:                 pip: 23.3.1
2024-02-06 16:44:16,891:INFO:          setuptools: 68.0.0
2024-02-06 16:44:16,891:INFO:             pycaret: 3.2.0
2024-02-06 16:44:16,891:INFO:             IPython: 8.15.0
2024-02-06 16:44:16,891:INFO:          ipywidgets: 8.0.4
2024-02-06 16:44:16,891:INFO:                tqdm: 4.65.0
2024-02-06 16:44:16,891:INFO:               numpy: 1.24.2
2024-02-06 16:44:16,892:INFO:              pandas: 1.5.3
2024-02-06 16:44:16,892:INFO:              jinja2: 3.1.2
2024-02-06 16:44:16,892:INFO:               scipy: 1.10.1
2024-02-06 16:44:16,892:INFO:              joblib: 1.2.0
2024-02-06 16:44:16,892:INFO:             sklearn: 1.2.2
2024-02-06 16:44:16,892:INFO:                pyod: 1.0.9
2024-02-06 16:44:16,892:INFO:            imblearn: 0.11.0
2024-02-06 16:44:16,892:INFO:   category_encoders: 2.6.3
2024-02-06 16:44:16,892:INFO:            lightgbm: 4.1.0
2024-02-06 16:44:16,892:INFO:               numba: 0.58.1
2024-02-06 16:44:16,892:INFO:            requests: 2.31.0
2024-02-06 16:44:16,892:INFO:          matplotlib: 3.7.1
2024-02-06 16:44:16,893:INFO:          scikitplot: 0.3.7
2024-02-06 16:44:16,893:INFO:         yellowbrick: 1.5
2024-02-06 16:44:16,893:INFO:              plotly: 5.9.0
2024-02-06 16:44:16,893:INFO:    plotly-resampler: Not installed
2024-02-06 16:44:16,893:INFO:             kaleido: 0.2.1
2024-02-06 16:44:16,893:INFO:           schemdraw: 0.15
2024-02-06 16:44:16,893:INFO:         statsmodels: 0.14.0
2024-02-06 16:44:16,893:INFO:              sktime: 0.21.1
2024-02-06 16:44:16,893:INFO:               tbats: 1.1.3
2024-02-06 16:44:16,893:INFO:            pmdarima: 2.0.3
2024-02-06 16:44:16,893:INFO:              psutil: 5.9.0
2024-02-06 16:44:16,893:INFO:          markupsafe: 2.1.1
2024-02-06 16:44:16,893:INFO:             pickle5: Not installed
2024-02-06 16:44:16,893:INFO:         cloudpickle: 2.2.1
2024-02-06 16:44:16,893:INFO:         deprecation: 2.1.0
2024-02-06 16:44:16,893:INFO:              xxhash: 2.0.2
2024-02-06 16:44:16,893:INFO:           wurlitzer: 3.0.2
2024-02-06 16:44:16,893:INFO:PyCaret optional dependencies:
2024-02-06 16:44:16,918:INFO:                shap: Not installed
2024-02-06 16:44:16,918:INFO:           interpret: Not installed
2024-02-06 16:44:16,918:INFO:                umap: Not installed
2024-02-06 16:44:16,918:INFO:     ydata_profiling: Not installed
2024-02-06 16:44:16,918:INFO:  explainerdashboard: Not installed
2024-02-06 16:44:16,918:INFO:             autoviz: Not installed
2024-02-06 16:44:16,918:INFO:           fairlearn: Not installed
2024-02-06 16:44:16,918:INFO:          deepchecks: Not installed
2024-02-06 16:44:16,919:INFO:             xgboost: Not installed
2024-02-06 16:44:16,919:INFO:            catboost: Not installed
2024-02-06 16:44:16,919:INFO:              kmodes: Not installed
2024-02-06 16:44:16,919:INFO:             mlxtend: Not installed
2024-02-06 16:44:16,919:INFO:       statsforecast: Not installed
2024-02-06 16:44:16,919:INFO:        tune_sklearn: Not installed
2024-02-06 16:44:16,919:INFO:                 ray: Not installed
2024-02-06 16:44:16,919:INFO:            hyperopt: Not installed
2024-02-06 16:44:16,919:INFO:              optuna: Not installed
2024-02-06 16:44:16,919:INFO:               skopt: Not installed
2024-02-06 16:44:16,919:INFO:              mlflow: Not installed
2024-02-06 16:44:16,919:INFO:              gradio: Not installed
2024-02-06 16:44:16,919:INFO:             fastapi: Not installed
2024-02-06 16:44:16,919:INFO:             uvicorn: Not installed
2024-02-06 16:44:16,919:INFO:              m2cgen: Not installed
2024-02-06 16:44:16,919:INFO:           evidently: Not installed
2024-02-06 16:44:16,919:INFO:               fugue: Not installed
2024-02-06 16:44:16,919:INFO:           streamlit: Not installed
2024-02-06 16:44:16,919:INFO:             prophet: Not installed
2024-02-06 16:44:16,919:INFO:None
2024-02-06 16:44:16,919:INFO:Set up data.
2024-02-06 16:44:16,961:INFO:Set up folding strategy.
2024-02-06 16:44:16,961:INFO:Set up train/test split.
2024-02-06 16:44:16,961:INFO:Set up data.
2024-02-06 16:44:16,986:INFO:Set up index.
2024-02-06 16:44:16,991:INFO:Assigning column types.
2024-02-06 16:44:17,017:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2024-02-06 16:44:17,082:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2024-02-06 16:44:17,093:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2024-02-06 16:44:17,145:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,146:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,197:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2024-02-06 16:44:17,198:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2024-02-06 16:44:17,230:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,230:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,231:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2024-02-06 16:44:17,282:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2024-02-06 16:44:17,313:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,313:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,369:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2024-02-06 16:44:17,402:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,403:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,403:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2024-02-06 16:44:17,485:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,485:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,571:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,571:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,582:INFO:Preparing preprocessing pipeline...
2024-02-06 16:44:17,585:INFO:Set up simple imputation.
2024-02-06 16:44:17,587:INFO:Set up column name cleaning.
2024-02-06 16:44:17,653:INFO:Finished creating preprocessing pipeline.
2024-02-06 16:44:17,664:INFO:Pipeline: Pipeline(memory=FastMemory(location=/var/folders/kw/4f743mkj0mzb2f42sdfvy9jw0000gn/T/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['accelX(g)', 'accelY(g)',
                                             'accelZ(g)', 'accelUserX(g)',
                                             'accelUserY(g)', 'accelUserZ(g)',
                                             'gyroX(rad/s)', 'gyroY(rad/s)',
                                             'gyroZ(rad/s)', 'Roll(rads)',
                                             'Pitch(rads)', 'Yaw(rads)', 'Lat',
                                             'Long', 'Speed(...
                 TransformerWrapper(exclude=None, include=[],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='most_frequent',
                                                              verbose='deprecated'))),
                ('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+')))],
         verbose=False)
2024-02-06 16:44:17,664:INFO:Creating final display dataframe.
2024-02-06 16:44:17,853:INFO:Setup _display_container:                     Description             Value
0                    Session id                42
1                        Target           on_lift
2                   Target type            Binary
3           Original data shape       (48509, 25)
4        Transformed data shape       (48509, 25)
5   Transformed train set shape       (38807, 25)
6    Transformed test set shape        (9702, 25)
7              Numeric features                24
8                    Preprocess              True
9               Imputation type            simple
10           Numeric imputation              mean
11       Categorical imputation              mode
12               Fold Generator   StratifiedKFold
13                  Fold Number                10
14                     CPU Jobs                -1
15                      Use GPU             False
16               Log Experiment             False
17              Experiment Name  clf-default-name
18                          USI              9edf
2024-02-06 16:44:17,989:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:17,989:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:18,102:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:18,102:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2024-02-06 16:44:18,103:INFO:setup() successfully completed in 1.53s...............
2024-02-06 16:45:05,372:INFO:Initializing compare_models()
2024-02-06 16:45:05,373:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, include=None, fold=5, round=4, cross_validation=True, sort=F1, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, 'include': None, 'exclude': None, 'fold': 5, 'round': 4, 'cross_validation': True, 'sort': 'F1', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2024-02-06 16:45:05,373:INFO:Checking exceptions
2024-02-06 16:45:05,403:INFO:Preparing display monitor
2024-02-06 16:45:05,579:INFO:Initializing Logistic Regression
2024-02-06 16:45:05,580:INFO:Total runtime is 1.3045469919840495e-05 minutes
2024-02-06 16:45:05,589:INFO:SubProcess create_model() called ==================================
2024-02-06 16:45:05,592:INFO:Initializing create_model()
2024-02-06 16:45:05,592:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=lr, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:45:05,592:INFO:Checking exceptions
2024-02-06 16:45:05,592:INFO:Importing libraries
2024-02-06 16:45:05,594:INFO:Copying training dataset
2024-02-06 16:45:05,638:INFO:Defining folds
2024-02-06 16:45:05,638:INFO:Declaring metric variables
2024-02-06 16:45:05,646:INFO:Importing untrained model
2024-02-06 16:45:05,656:INFO:Logistic Regression Imported successfully
2024-02-06 16:45:05,669:INFO:Starting cross validation
2024-02-06 16:45:05,671:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:45:17,362:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-02-06 16:45:17,385:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-02-06 16:45:17,397:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-02-06 16:45:17,431:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-02-06 16:45:17,436:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-02-06 16:45:17,644:INFO:Calculating mean and std
2024-02-06 16:45:17,648:INFO:Creating metrics dataframe
2024-02-06 16:45:17,660:INFO:Uploading results into container
2024-02-06 16:45:17,662:INFO:Uploading model into container now
2024-02-06 16:45:17,663:INFO:_master_model_container: 1
2024-02-06 16:45:17,663:INFO:_display_container: 2
2024-02-06 16:45:17,663:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2024-02-06 16:45:17,664:INFO:create_model() successfully completed......................................
2024-02-06 16:45:17,871:INFO:SubProcess create_model() end ==================================
2024-02-06 16:45:17,871:INFO:Creating metrics dataframe
2024-02-06 16:45:17,891:INFO:Initializing K Neighbors Classifier
2024-02-06 16:45:17,891:INFO:Total runtime is 0.20520568291346233 minutes
2024-02-06 16:45:17,897:INFO:SubProcess create_model() called ==================================
2024-02-06 16:45:17,898:INFO:Initializing create_model()
2024-02-06 16:45:17,898:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=knn, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:45:17,898:INFO:Checking exceptions
2024-02-06 16:45:17,898:INFO:Importing libraries
2024-02-06 16:45:17,898:INFO:Copying training dataset
2024-02-06 16:45:17,931:INFO:Defining folds
2024-02-06 16:45:17,931:INFO:Declaring metric variables
2024-02-06 16:45:17,937:INFO:Importing untrained model
2024-02-06 16:45:17,946:INFO:K Neighbors Classifier Imported successfully
2024-02-06 16:45:17,962:INFO:Starting cross validation
2024-02-06 16:45:17,964:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:45:26,396:INFO:Calculating mean and std
2024-02-06 16:45:26,398:INFO:Creating metrics dataframe
2024-02-06 16:45:26,402:INFO:Uploading results into container
2024-02-06 16:45:26,403:INFO:Uploading model into container now
2024-02-06 16:45:26,404:INFO:_master_model_container: 2
2024-02-06 16:45:26,404:INFO:_display_container: 2
2024-02-06 16:45:26,405:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2024-02-06 16:45:26,405:INFO:create_model() successfully completed......................................
2024-02-06 16:45:26,557:INFO:SubProcess create_model() end ==================================
2024-02-06 16:45:26,557:INFO:Creating metrics dataframe
2024-02-06 16:45:26,574:INFO:Initializing Naive Bayes
2024-02-06 16:45:26,574:INFO:Total runtime is 0.3499239802360535 minutes
2024-02-06 16:45:26,582:INFO:SubProcess create_model() called ==================================
2024-02-06 16:45:26,583:INFO:Initializing create_model()
2024-02-06 16:45:26,583:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=nb, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:45:26,583:INFO:Checking exceptions
2024-02-06 16:45:26,583:INFO:Importing libraries
2024-02-06 16:45:26,583:INFO:Copying training dataset
2024-02-06 16:45:26,616:INFO:Defining folds
2024-02-06 16:45:26,616:INFO:Declaring metric variables
2024-02-06 16:45:26,624:INFO:Importing untrained model
2024-02-06 16:45:26,633:INFO:Naive Bayes Imported successfully
2024-02-06 16:45:26,649:INFO:Starting cross validation
2024-02-06 16:45:26,650:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:45:27,013:INFO:Calculating mean and std
2024-02-06 16:45:27,018:INFO:Creating metrics dataframe
2024-02-06 16:45:27,028:INFO:Uploading results into container
2024-02-06 16:45:27,029:INFO:Uploading model into container now
2024-02-06 16:45:27,031:INFO:_master_model_container: 3
2024-02-06 16:45:27,031:INFO:_display_container: 2
2024-02-06 16:45:27,032:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2024-02-06 16:45:27,032:INFO:create_model() successfully completed......................................
2024-02-06 16:45:27,211:INFO:SubProcess create_model() end ==================================
2024-02-06 16:45:27,211:INFO:Creating metrics dataframe
2024-02-06 16:45:27,230:INFO:Initializing Decision Tree Classifier
2024-02-06 16:45:27,230:INFO:Total runtime is 0.3608532309532166 minutes
2024-02-06 16:45:27,236:INFO:SubProcess create_model() called ==================================
2024-02-06 16:45:27,237:INFO:Initializing create_model()
2024-02-06 16:45:27,237:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=dt, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:45:27,237:INFO:Checking exceptions
2024-02-06 16:45:27,238:INFO:Importing libraries
2024-02-06 16:45:27,238:INFO:Copying training dataset
2024-02-06 16:45:27,270:INFO:Defining folds
2024-02-06 16:45:27,271:INFO:Declaring metric variables
2024-02-06 16:45:27,280:INFO:Importing untrained model
2024-02-06 16:45:27,290:INFO:Decision Tree Classifier Imported successfully
2024-02-06 16:45:27,307:INFO:Starting cross validation
2024-02-06 16:45:27,310:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:45:31,265:INFO:Calculating mean and std
2024-02-06 16:45:31,266:INFO:Creating metrics dataframe
2024-02-06 16:45:31,271:INFO:Uploading results into container
2024-02-06 16:45:31,272:INFO:Uploading model into container now
2024-02-06 16:45:31,273:INFO:_master_model_container: 4
2024-02-06 16:45:31,274:INFO:_display_container: 2
2024-02-06 16:45:31,275:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=42, splitter='best')
2024-02-06 16:45:31,275:INFO:create_model() successfully completed......................................
2024-02-06 16:45:31,436:INFO:SubProcess create_model() end ==================================
2024-02-06 16:45:31,437:INFO:Creating metrics dataframe
2024-02-06 16:45:31,455:INFO:Initializing SVM - Linear Kernel
2024-02-06 16:45:31,455:INFO:Total runtime is 0.4312738656997681 minutes
2024-02-06 16:45:31,461:INFO:SubProcess create_model() called ==================================
2024-02-06 16:45:31,462:INFO:Initializing create_model()
2024-02-06 16:45:31,462:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=svm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:45:31,463:INFO:Checking exceptions
2024-02-06 16:45:31,463:INFO:Importing libraries
2024-02-06 16:45:31,463:INFO:Copying training dataset
2024-02-06 16:45:31,493:INFO:Defining folds
2024-02-06 16:45:31,493:INFO:Declaring metric variables
2024-02-06 16:45:31,501:INFO:Importing untrained model
2024-02-06 16:45:31,508:INFO:SVM - Linear Kernel Imported successfully
2024-02-06 16:45:31,522:INFO:Starting cross validation
2024-02-06 16:45:31,524:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:45:32,218:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-06 16:45:32,218:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-06 16:45:32,304:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-06 16:45:32,338:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-06 16:45:32,379:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-06 16:45:32,509:INFO:Calculating mean and std
2024-02-06 16:45:32,511:INFO:Creating metrics dataframe
2024-02-06 16:45:32,517:INFO:Uploading results into container
2024-02-06 16:45:32,518:INFO:Uploading model into container now
2024-02-06 16:45:32,518:INFO:_master_model_container: 5
2024-02-06 16:45:32,519:INFO:_display_container: 2
2024-02-06 16:45:32,519:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=42, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2024-02-06 16:45:32,519:INFO:create_model() successfully completed......................................
2024-02-06 16:45:32,667:INFO:SubProcess create_model() end ==================================
2024-02-06 16:45:32,667:INFO:Creating metrics dataframe
2024-02-06 16:45:32,688:INFO:Initializing Ridge Classifier
2024-02-06 16:45:32,688:INFO:Total runtime is 0.4518231987953186 minutes
2024-02-06 16:45:32,695:INFO:SubProcess create_model() called ==================================
2024-02-06 16:45:32,695:INFO:Initializing create_model()
2024-02-06 16:45:32,696:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=ridge, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:45:32,696:INFO:Checking exceptions
2024-02-06 16:45:32,696:INFO:Importing libraries
2024-02-06 16:45:32,696:INFO:Copying training dataset
2024-02-06 16:45:32,726:INFO:Defining folds
2024-02-06 16:45:32,726:INFO:Declaring metric variables
2024-02-06 16:45:32,736:INFO:Importing untrained model
2024-02-06 16:45:32,744:INFO:Ridge Classifier Imported successfully
2024-02-06 16:45:32,759:INFO:Starting cross validation
2024-02-06 16:45:32,761:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:45:32,905:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=5.42016e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-06 16:45:32,925:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=5.21184e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-06 16:45:32,937:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-06 16:45:32,952:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-06 16:45:32,952:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.82418e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-06 16:45:32,961:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.81825e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-06 16:45:32,961:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=6.2473e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-06 16:45:32,975:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-06 16:45:32,981:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-06 16:45:32,983:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-06 16:45:33,118:INFO:Calculating mean and std
2024-02-06 16:45:33,119:INFO:Creating metrics dataframe
2024-02-06 16:45:33,123:INFO:Uploading results into container
2024-02-06 16:45:33,123:INFO:Uploading model into container now
2024-02-06 16:45:33,124:INFO:_master_model_container: 6
2024-02-06 16:45:33,124:INFO:_display_container: 2
2024-02-06 16:45:33,124:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=42, solver='auto',
                tol=0.0001)
2024-02-06 16:45:33,125:INFO:create_model() successfully completed......................................
2024-02-06 16:45:33,257:INFO:SubProcess create_model() end ==================================
2024-02-06 16:45:33,257:INFO:Creating metrics dataframe
2024-02-06 16:45:33,272:INFO:Initializing Random Forest Classifier
2024-02-06 16:45:33,272:INFO:Total runtime is 0.4615519126256307 minutes
2024-02-06 16:45:33,279:INFO:SubProcess create_model() called ==================================
2024-02-06 16:45:33,279:INFO:Initializing create_model()
2024-02-06 16:45:33,279:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=rf, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:45:33,279:INFO:Checking exceptions
2024-02-06 16:45:33,279:INFO:Importing libraries
2024-02-06 16:45:33,279:INFO:Copying training dataset
2024-02-06 16:45:33,312:INFO:Defining folds
2024-02-06 16:45:33,313:INFO:Declaring metric variables
2024-02-06 16:45:33,321:INFO:Importing untrained model
2024-02-06 16:45:33,331:INFO:Random Forest Classifier Imported successfully
2024-02-06 16:45:33,347:INFO:Starting cross validation
2024-02-06 16:45:33,349:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:45:45,384:INFO:Calculating mean and std
2024-02-06 16:45:45,385:INFO:Creating metrics dataframe
2024-02-06 16:45:45,389:INFO:Uploading results into container
2024-02-06 16:45:45,390:INFO:Uploading model into container now
2024-02-06 16:45:45,391:INFO:_master_model_container: 7
2024-02-06 16:45:45,391:INFO:_display_container: 2
2024-02-06 16:45:45,392:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False)
2024-02-06 16:45:45,392:INFO:create_model() successfully completed......................................
2024-02-06 16:45:45,527:INFO:SubProcess create_model() end ==================================
2024-02-06 16:45:45,527:INFO:Creating metrics dataframe
2024-02-06 16:45:45,544:INFO:Initializing Quadratic Discriminant Analysis
2024-02-06 16:45:45,545:INFO:Total runtime is 0.666096568107605 minutes
2024-02-06 16:45:45,549:INFO:SubProcess create_model() called ==================================
2024-02-06 16:45:45,549:INFO:Initializing create_model()
2024-02-06 16:45:45,549:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=qda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:45:45,549:INFO:Checking exceptions
2024-02-06 16:45:45,549:INFO:Importing libraries
2024-02-06 16:45:45,550:INFO:Copying training dataset
2024-02-06 16:45:45,575:INFO:Defining folds
2024-02-06 16:45:45,575:INFO:Declaring metric variables
2024-02-06 16:45:45,582:INFO:Importing untrained model
2024-02-06 16:45:45,589:INFO:Quadratic Discriminant Analysis Imported successfully
2024-02-06 16:45:45,599:INFO:Starting cross validation
2024-02-06 16:45:45,600:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:45:46,049:INFO:Calculating mean and std
2024-02-06 16:45:46,051:INFO:Creating metrics dataframe
2024-02-06 16:45:46,055:INFO:Uploading results into container
2024-02-06 16:45:46,056:INFO:Uploading model into container now
2024-02-06 16:45:46,056:INFO:_master_model_container: 8
2024-02-06 16:45:46,056:INFO:_display_container: 2
2024-02-06 16:45:46,057:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2024-02-06 16:45:46,057:INFO:create_model() successfully completed......................................
2024-02-06 16:45:46,189:INFO:SubProcess create_model() end ==================================
2024-02-06 16:45:46,190:INFO:Creating metrics dataframe
2024-02-06 16:45:46,209:INFO:Initializing Ada Boost Classifier
2024-02-06 16:45:46,209:INFO:Total runtime is 0.6771711985270182 minutes
2024-02-06 16:45:46,214:INFO:SubProcess create_model() called ==================================
2024-02-06 16:45:46,215:INFO:Initializing create_model()
2024-02-06 16:45:46,215:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=ada, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:45:46,215:INFO:Checking exceptions
2024-02-06 16:45:46,216:INFO:Importing libraries
2024-02-06 16:45:46,216:INFO:Copying training dataset
2024-02-06 16:45:46,240:INFO:Defining folds
2024-02-06 16:45:46,240:INFO:Declaring metric variables
2024-02-06 16:45:46,246:INFO:Importing untrained model
2024-02-06 16:45:46,253:INFO:Ada Boost Classifier Imported successfully
2024-02-06 16:45:46,263:INFO:Starting cross validation
2024-02-06 16:45:46,264:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:45:51,794:INFO:Calculating mean and std
2024-02-06 16:45:51,795:INFO:Creating metrics dataframe
2024-02-06 16:45:51,798:INFO:Uploading results into container
2024-02-06 16:45:51,799:INFO:Uploading model into container now
2024-02-06 16:45:51,799:INFO:_master_model_container: 9
2024-02-06 16:45:51,799:INFO:_display_container: 2
2024-02-06 16:45:51,799:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=42)
2024-02-06 16:45:51,799:INFO:create_model() successfully completed......................................
2024-02-06 16:45:51,912:INFO:SubProcess create_model() end ==================================
2024-02-06 16:45:51,912:INFO:Creating metrics dataframe
2024-02-06 16:45:51,925:INFO:Initializing Gradient Boosting Classifier
2024-02-06 16:45:51,925:INFO:Total runtime is 0.7724440813064575 minutes
2024-02-06 16:45:51,930:INFO:SubProcess create_model() called ==================================
2024-02-06 16:45:51,930:INFO:Initializing create_model()
2024-02-06 16:45:51,930:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=gbc, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:45:51,930:INFO:Checking exceptions
2024-02-06 16:45:51,931:INFO:Importing libraries
2024-02-06 16:45:51,931:INFO:Copying training dataset
2024-02-06 16:45:51,951:INFO:Defining folds
2024-02-06 16:45:51,951:INFO:Declaring metric variables
2024-02-06 16:45:51,955:INFO:Importing untrained model
2024-02-06 16:45:51,959:INFO:Gradient Boosting Classifier Imported successfully
2024-02-06 16:45:51,970:INFO:Starting cross validation
2024-02-06 16:45:51,971:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:46:17,845:INFO:Calculating mean and std
2024-02-06 16:46:17,847:INFO:Creating metrics dataframe
2024-02-06 16:46:17,851:INFO:Uploading results into container
2024-02-06 16:46:17,852:INFO:Uploading model into container now
2024-02-06 16:46:17,852:INFO:_master_model_container: 10
2024-02-06 16:46:17,852:INFO:_display_container: 2
2024-02-06 16:46:17,853:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2024-02-06 16:46:17,853:INFO:create_model() successfully completed......................................
2024-02-06 16:46:17,982:INFO:SubProcess create_model() end ==================================
2024-02-06 16:46:17,982:INFO:Creating metrics dataframe
2024-02-06 16:46:18,001:INFO:Initializing Linear Discriminant Analysis
2024-02-06 16:46:18,001:INFO:Total runtime is 1.2070440332094827 minutes
2024-02-06 16:46:18,007:INFO:SubProcess create_model() called ==================================
2024-02-06 16:46:18,007:INFO:Initializing create_model()
2024-02-06 16:46:18,007:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=lda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:46:18,007:INFO:Checking exceptions
2024-02-06 16:46:18,008:INFO:Importing libraries
2024-02-06 16:46:18,008:INFO:Copying training dataset
2024-02-06 16:46:18,031:INFO:Defining folds
2024-02-06 16:46:18,031:INFO:Declaring metric variables
2024-02-06 16:46:18,037:INFO:Importing untrained model
2024-02-06 16:46:18,043:INFO:Linear Discriminant Analysis Imported successfully
2024-02-06 16:46:18,055:INFO:Starting cross validation
2024-02-06 16:46:18,057:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:46:18,585:INFO:Calculating mean and std
2024-02-06 16:46:18,586:INFO:Creating metrics dataframe
2024-02-06 16:46:18,590:INFO:Uploading results into container
2024-02-06 16:46:18,591:INFO:Uploading model into container now
2024-02-06 16:46:18,592:INFO:_master_model_container: 11
2024-02-06 16:46:18,592:INFO:_display_container: 2
2024-02-06 16:46:18,592:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2024-02-06 16:46:18,592:INFO:create_model() successfully completed......................................
2024-02-06 16:46:18,729:INFO:SubProcess create_model() end ==================================
2024-02-06 16:46:18,729:INFO:Creating metrics dataframe
2024-02-06 16:46:18,750:INFO:Initializing Extra Trees Classifier
2024-02-06 16:46:18,750:INFO:Total runtime is 1.219516634941101 minutes
2024-02-06 16:46:18,755:INFO:SubProcess create_model() called ==================================
2024-02-06 16:46:18,756:INFO:Initializing create_model()
2024-02-06 16:46:18,756:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=et, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:46:18,756:INFO:Checking exceptions
2024-02-06 16:46:18,756:INFO:Importing libraries
2024-02-06 16:46:18,756:INFO:Copying training dataset
2024-02-06 16:46:18,780:INFO:Defining folds
2024-02-06 16:46:18,780:INFO:Declaring metric variables
2024-02-06 16:46:18,787:INFO:Importing untrained model
2024-02-06 16:46:18,796:INFO:Extra Trees Classifier Imported successfully
2024-02-06 16:46:18,805:INFO:Starting cross validation
2024-02-06 16:46:18,807:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:46:22,368:INFO:Calculating mean and std
2024-02-06 16:46:22,370:INFO:Creating metrics dataframe
2024-02-06 16:46:22,374:INFO:Uploading results into container
2024-02-06 16:46:22,375:INFO:Uploading model into container now
2024-02-06 16:46:22,376:INFO:_master_model_container: 12
2024-02-06 16:46:22,376:INFO:_display_container: 2
2024-02-06 16:46:22,376:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=42, verbose=0, warm_start=False)
2024-02-06 16:46:22,376:INFO:create_model() successfully completed......................................
2024-02-06 16:46:22,506:INFO:SubProcess create_model() end ==================================
2024-02-06 16:46:22,506:INFO:Creating metrics dataframe
2024-02-06 16:46:22,524:INFO:Initializing Light Gradient Boosting Machine
2024-02-06 16:46:22,524:INFO:Total runtime is 1.2824252684911093 minutes
2024-02-06 16:46:22,529:INFO:SubProcess create_model() called ==================================
2024-02-06 16:46:22,529:INFO:Initializing create_model()
2024-02-06 16:46:22,529:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=lightgbm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:46:22,529:INFO:Checking exceptions
2024-02-06 16:46:22,529:INFO:Importing libraries
2024-02-06 16:46:22,529:INFO:Copying training dataset
2024-02-06 16:46:22,552:INFO:Defining folds
2024-02-06 16:46:22,552:INFO:Declaring metric variables
2024-02-06 16:46:22,557:INFO:Importing untrained model
2024-02-06 16:46:22,562:INFO:Light Gradient Boosting Machine Imported successfully
2024-02-06 16:46:22,570:INFO:Starting cross validation
2024-02-06 16:46:22,571:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:46:27,778:INFO:Calculating mean and std
2024-02-06 16:46:27,780:INFO:Creating metrics dataframe
2024-02-06 16:46:27,785:INFO:Uploading results into container
2024-02-06 16:46:27,786:INFO:Uploading model into container now
2024-02-06 16:46:27,786:INFO:_master_model_container: 13
2024-02-06 16:46:27,787:INFO:_display_container: 2
2024-02-06 16:46:27,787:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2024-02-06 16:46:27,788:INFO:create_model() successfully completed......................................
2024-02-06 16:46:27,929:INFO:SubProcess create_model() end ==================================
2024-02-06 16:46:27,929:INFO:Creating metrics dataframe
2024-02-06 16:46:27,948:INFO:Initializing Dummy Classifier
2024-02-06 16:46:27,948:INFO:Total runtime is 1.3728283007939657 minutes
2024-02-06 16:46:27,953:INFO:SubProcess create_model() called ==================================
2024-02-06 16:46:27,954:INFO:Initializing create_model()
2024-02-06 16:46:27,954:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=dummy, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee095dbf70>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:46:27,954:INFO:Checking exceptions
2024-02-06 16:46:27,954:INFO:Importing libraries
2024-02-06 16:46:27,954:INFO:Copying training dataset
2024-02-06 16:46:27,978:INFO:Defining folds
2024-02-06 16:46:27,978:INFO:Declaring metric variables
2024-02-06 16:46:27,983:INFO:Importing untrained model
2024-02-06 16:46:27,988:INFO:Dummy Classifier Imported successfully
2024-02-06 16:46:27,999:INFO:Starting cross validation
2024-02-06 16:46:28,001:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:46:28,121:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-06 16:46:28,123:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-06 16:46:28,129:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-06 16:46:28,140:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-06 16:46:28,149:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-06 16:46:28,263:INFO:Calculating mean and std
2024-02-06 16:46:28,265:INFO:Creating metrics dataframe
2024-02-06 16:46:28,269:INFO:Uploading results into container
2024-02-06 16:46:28,269:INFO:Uploading model into container now
2024-02-06 16:46:28,270:INFO:_master_model_container: 14
2024-02-06 16:46:28,270:INFO:_display_container: 2
2024-02-06 16:46:28,271:INFO:DummyClassifier(constant=None, random_state=42, strategy='prior')
2024-02-06 16:46:28,271:INFO:create_model() successfully completed......................................
2024-02-06 16:46:28,403:INFO:SubProcess create_model() end ==================================
2024-02-06 16:46:28,403:INFO:Creating metrics dataframe
2024-02-06 16:46:28,435:INFO:Initializing create_model()
2024-02-06 16:46:28,436:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0), fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:46:28,436:INFO:Checking exceptions
2024-02-06 16:46:28,438:INFO:Importing libraries
2024-02-06 16:46:28,438:INFO:Copying training dataset
2024-02-06 16:46:28,461:INFO:Defining folds
2024-02-06 16:46:28,461:INFO:Declaring metric variables
2024-02-06 16:46:28,461:INFO:Importing untrained model
2024-02-06 16:46:28,461:INFO:Declaring custom model
2024-02-06 16:46:28,462:INFO:Light Gradient Boosting Machine Imported successfully
2024-02-06 16:46:28,463:INFO:Cross validation set to False
2024-02-06 16:46:28,463:INFO:Fitting Model
2024-02-06 16:46:28,560:INFO:[LightGBM] [Info] Number of positive: 7596, number of negative: 31211
2024-02-06 16:46:28,564:INFO:[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002877 seconds.
2024-02-06 16:46:28,564:INFO:You can set `force_col_wise=true` to remove the overhead.
2024-02-06 16:46:28,564:INFO:[LightGBM] [Info] Total Bins 6054
2024-02-06 16:46:28,565:INFO:[LightGBM] [Info] Number of data points in the train set: 38807, number of used features: 24
2024-02-06 16:46:28,566:INFO:[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.195738 -> initscore=-1.413149
2024-02-06 16:46:28,566:INFO:[LightGBM] [Info] Start training from score -1.413149
2024-02-06 16:46:28,859:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2024-02-06 16:46:28,859:INFO:create_model() successfully completed......................................
2024-02-06 16:46:29,044:INFO:_master_model_container: 14
2024-02-06 16:46:29,045:INFO:_display_container: 2
2024-02-06 16:46:29,046:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2024-02-06 16:46:29,046:INFO:compare_models() successfully completed......................................
2024-02-06 16:48:58,535:INFO:Initializing create_model()
2024-02-06 16:48:58,535:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=rf, fold=5, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=True, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:48:58,536:INFO:Checking exceptions
2024-02-06 16:48:58,567:INFO:Importing libraries
2024-02-06 16:48:58,568:INFO:Copying training dataset
2024-02-06 16:48:58,597:INFO:Defining folds
2024-02-06 16:48:58,597:INFO:Declaring metric variables
2024-02-06 16:48:58,602:INFO:Importing untrained model
2024-02-06 16:48:58,609:INFO:Random Forest Classifier Imported successfully
2024-02-06 16:48:58,641:INFO:Starting cross validation
2024-02-06 16:48:58,644:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:49:09,196:INFO:Calculating mean and std
2024-02-06 16:49:09,198:INFO:Creating metrics dataframe
2024-02-06 16:49:09,205:INFO:Finalizing model
2024-02-06 16:49:12,076:INFO:Uploading results into container
2024-02-06 16:49:12,077:INFO:Uploading model into container now
2024-02-06 16:49:12,088:INFO:_master_model_container: 15
2024-02-06 16:49:12,088:INFO:_display_container: 3
2024-02-06 16:49:12,089:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False)
2024-02-06 16:49:12,089:INFO:create_model() successfully completed......................................
2024-02-06 16:49:12,238:INFO:Initializing create_model()
2024-02-06 16:49:12,239:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=et, fold=5, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=True, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:49:12,239:INFO:Checking exceptions
2024-02-06 16:49:12,262:INFO:Importing libraries
2024-02-06 16:49:12,262:INFO:Copying training dataset
2024-02-06 16:49:12,286:INFO:Defining folds
2024-02-06 16:49:12,287:INFO:Declaring metric variables
2024-02-06 16:49:12,292:INFO:Importing untrained model
2024-02-06 16:49:12,297:INFO:Extra Trees Classifier Imported successfully
2024-02-06 16:49:12,306:INFO:Starting cross validation
2024-02-06 16:49:12,308:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:49:15,905:INFO:Calculating mean and std
2024-02-06 16:49:15,906:INFO:Creating metrics dataframe
2024-02-06 16:49:15,912:INFO:Finalizing model
2024-02-06 16:49:16,626:INFO:Uploading results into container
2024-02-06 16:49:16,627:INFO:Uploading model into container now
2024-02-06 16:49:16,637:INFO:_master_model_container: 16
2024-02-06 16:49:16,638:INFO:_display_container: 4
2024-02-06 16:49:16,638:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=42, verbose=0, warm_start=False)
2024-02-06 16:49:16,638:INFO:create_model() successfully completed......................................
2024-02-06 16:49:16,778:INFO:Initializing create_model()
2024-02-06 16:49:16,778:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=lightgbm, fold=5, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=True, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:49:16,779:INFO:Checking exceptions
2024-02-06 16:49:16,804:INFO:Importing libraries
2024-02-06 16:49:16,804:INFO:Copying training dataset
2024-02-06 16:49:16,831:INFO:Defining folds
2024-02-06 16:49:16,832:INFO:Declaring metric variables
2024-02-06 16:49:16,836:INFO:Importing untrained model
2024-02-06 16:49:16,841:INFO:Light Gradient Boosting Machine Imported successfully
2024-02-06 16:49:16,853:INFO:Starting cross validation
2024-02-06 16:49:16,854:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:49:21,863:INFO:Calculating mean and std
2024-02-06 16:49:21,865:INFO:Creating metrics dataframe
2024-02-06 16:49:21,872:INFO:Finalizing model
2024-02-06 16:49:21,973:INFO:[LightGBM] [Info] Number of positive: 7596, number of negative: 31211
2024-02-06 16:49:21,978:INFO:[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004658 seconds.
2024-02-06 16:49:21,978:INFO:You can set `force_col_wise=true` to remove the overhead.
2024-02-06 16:49:21,979:INFO:[LightGBM] [Info] Total Bins 6054
2024-02-06 16:49:21,979:INFO:[LightGBM] [Info] Number of data points in the train set: 38807, number of used features: 24
2024-02-06 16:49:21,980:INFO:[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.195738 -> initscore=-1.413149
2024-02-06 16:49:21,980:INFO:[LightGBM] [Info] Start training from score -1.413149
2024-02-06 16:49:22,261:INFO:Uploading results into container
2024-02-06 16:49:22,262:INFO:Uploading model into container now
2024-02-06 16:49:22,277:INFO:_master_model_container: 17
2024-02-06 16:49:22,277:INFO:_display_container: 5
2024-02-06 16:49:22,278:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2024-02-06 16:49:22,279:INFO:create_model() successfully completed......................................
2024-02-06 16:50:15,855:INFO:Initializing create_model()
2024-02-06 16:50:15,856:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=lightgbm, fold=5, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=True, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:50:15,856:INFO:Checking exceptions
2024-02-06 16:50:15,883:INFO:Importing libraries
2024-02-06 16:50:15,884:INFO:Copying training dataset
2024-02-06 16:50:15,961:INFO:Defining folds
2024-02-06 16:50:15,961:INFO:Declaring metric variables
2024-02-06 16:50:15,988:INFO:Importing untrained model
2024-02-06 16:50:15,999:INFO:Light Gradient Boosting Machine Imported successfully
2024-02-06 16:50:16,010:INFO:Starting cross validation
2024-02-06 16:50:16,011:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:50:21,015:INFO:Calculating mean and std
2024-02-06 16:50:21,017:INFO:Creating metrics dataframe
2024-02-06 16:50:21,025:INFO:Finalizing model
2024-02-06 16:50:21,127:INFO:[LightGBM] [Info] Number of positive: 7596, number of negative: 31211
2024-02-06 16:50:21,131:INFO:[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002856 seconds.
2024-02-06 16:50:21,131:INFO:You can set `force_col_wise=true` to remove the overhead.
2024-02-06 16:50:21,131:INFO:[LightGBM] [Info] Total Bins 6054
2024-02-06 16:50:21,132:INFO:[LightGBM] [Info] Number of data points in the train set: 38807, number of used features: 24
2024-02-06 16:50:21,132:INFO:[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.195738 -> initscore=-1.413149
2024-02-06 16:50:21,132:INFO:[LightGBM] [Info] Start training from score -1.413149
2024-02-06 16:50:21,452:INFO:Uploading results into container
2024-02-06 16:50:21,453:INFO:Uploading model into container now
2024-02-06 16:50:21,466:INFO:_master_model_container: 18
2024-02-06 16:50:21,466:INFO:_display_container: 6
2024-02-06 16:50:21,467:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2024-02-06 16:50:21,467:INFO:create_model() successfully completed......................................
2024-02-06 16:50:21,620:INFO:Initializing create_model()
2024-02-06 16:50:21,620:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=et, fold=5, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=True, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:50:21,620:INFO:Checking exceptions
2024-02-06 16:50:21,649:INFO:Importing libraries
2024-02-06 16:50:21,649:INFO:Copying training dataset
2024-02-06 16:50:21,674:INFO:Defining folds
2024-02-06 16:50:21,675:INFO:Declaring metric variables
2024-02-06 16:50:21,680:INFO:Importing untrained model
2024-02-06 16:50:21,686:INFO:Extra Trees Classifier Imported successfully
2024-02-06 16:50:21,706:INFO:Starting cross validation
2024-02-06 16:50:21,708:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:50:25,626:INFO:Calculating mean and std
2024-02-06 16:50:25,628:INFO:Creating metrics dataframe
2024-02-06 16:50:25,636:INFO:Finalizing model
2024-02-06 16:50:26,479:INFO:Uploading results into container
2024-02-06 16:50:26,480:INFO:Uploading model into container now
2024-02-06 16:50:26,495:INFO:_master_model_container: 19
2024-02-06 16:50:26,496:INFO:_display_container: 7
2024-02-06 16:50:26,497:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=42, verbose=0, warm_start=False)
2024-02-06 16:50:26,497:INFO:create_model() successfully completed......................................
2024-02-06 16:50:26,710:INFO:Initializing create_model()
2024-02-06 16:50:26,710:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=rf, fold=5, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=True, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 16:50:26,711:INFO:Checking exceptions
2024-02-06 16:50:26,739:INFO:Importing libraries
2024-02-06 16:50:26,740:INFO:Copying training dataset
2024-02-06 16:50:26,765:INFO:Defining folds
2024-02-06 16:50:26,765:INFO:Declaring metric variables
2024-02-06 16:50:26,770:INFO:Importing untrained model
2024-02-06 16:50:26,775:INFO:Random Forest Classifier Imported successfully
2024-02-06 16:50:26,786:INFO:Starting cross validation
2024-02-06 16:50:26,787:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 16:50:37,764:INFO:Calculating mean and std
2024-02-06 16:50:37,766:INFO:Creating metrics dataframe
2024-02-06 16:50:37,772:INFO:Finalizing model
2024-02-06 16:50:40,816:INFO:Uploading results into container
2024-02-06 16:50:40,817:INFO:Uploading model into container now
2024-02-06 16:50:40,829:INFO:_master_model_container: 20
2024-02-06 16:50:40,829:INFO:_display_container: 8
2024-02-06 16:50:40,830:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False)
2024-02-06 16:50:40,830:INFO:create_model() successfully completed......................................
2024-02-06 18:06:55,824:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 9 (	) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)

2024-02-06 18:07:19,811:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/IPython/core/pylabtools.py:152: UserWarning: Glyph 9 (	) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)

2024-02-06 19:23:39,548:INFO:Initializing compare_models()
2024-02-06 19:23:39,554:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, include=None, fold=5, round=4, cross_validation=True, sort=F1, n_select=3, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, 'include': None, 'exclude': None, 'fold': 5, 'round': 4, 'cross_validation': True, 'sort': 'F1', 'n_select': 3, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2024-02-06 19:23:39,555:INFO:Checking exceptions
2024-02-06 19:23:39,567:INFO:Preparing display monitor
2024-02-06 19:23:39,614:INFO:Initializing Logistic Regression
2024-02-06 19:23:39,614:INFO:Total runtime is 7.430712381998698e-06 minutes
2024-02-06 19:23:39,625:INFO:SubProcess create_model() called ==================================
2024-02-06 19:23:39,626:INFO:Initializing create_model()
2024-02-06 19:23:39,626:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=lr, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:23:39,627:INFO:Checking exceptions
2024-02-06 19:23:39,627:INFO:Importing libraries
2024-02-06 19:23:39,628:INFO:Copying training dataset
2024-02-06 19:23:39,655:INFO:Defining folds
2024-02-06 19:23:39,655:INFO:Declaring metric variables
2024-02-06 19:23:39,660:INFO:Importing untrained model
2024-02-06 19:23:39,666:INFO:Logistic Regression Imported successfully
2024-02-06 19:23:39,679:INFO:Starting cross validation
2024-02-06 19:23:39,680:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:23:49,312:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-02-06 19:23:49,322:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-02-06 19:23:49,330:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-02-06 19:23:49,333:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-02-06 19:23:49,342:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2024-02-06 19:23:49,507:INFO:Calculating mean and std
2024-02-06 19:23:49,510:INFO:Creating metrics dataframe
2024-02-06 19:23:49,519:INFO:Uploading results into container
2024-02-06 19:23:49,520:INFO:Uploading model into container now
2024-02-06 19:23:49,521:INFO:_master_model_container: 21
2024-02-06 19:23:49,521:INFO:_display_container: 9
2024-02-06 19:23:49,522:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2024-02-06 19:23:49,522:INFO:create_model() successfully completed......................................
2024-02-06 19:23:49,739:INFO:SubProcess create_model() end ==================================
2024-02-06 19:23:49,739:INFO:Creating metrics dataframe
2024-02-06 19:23:49,756:INFO:Initializing K Neighbors Classifier
2024-02-06 19:23:49,756:INFO:Total runtime is 0.16904424826304118 minutes
2024-02-06 19:23:49,762:INFO:SubProcess create_model() called ==================================
2024-02-06 19:23:49,763:INFO:Initializing create_model()
2024-02-06 19:23:49,763:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=knn, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:23:49,763:INFO:Checking exceptions
2024-02-06 19:23:49,763:INFO:Importing libraries
2024-02-06 19:23:49,763:INFO:Copying training dataset
2024-02-06 19:23:49,793:INFO:Defining folds
2024-02-06 19:23:49,794:INFO:Declaring metric variables
2024-02-06 19:23:49,799:INFO:Importing untrained model
2024-02-06 19:23:49,804:INFO:K Neighbors Classifier Imported successfully
2024-02-06 19:23:49,816:INFO:Starting cross validation
2024-02-06 19:23:49,818:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:23:56,294:INFO:Calculating mean and std
2024-02-06 19:23:56,295:INFO:Creating metrics dataframe
2024-02-06 19:23:56,301:INFO:Uploading results into container
2024-02-06 19:23:56,302:INFO:Uploading model into container now
2024-02-06 19:23:56,303:INFO:_master_model_container: 22
2024-02-06 19:23:56,303:INFO:_display_container: 9
2024-02-06 19:23:56,303:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2024-02-06 19:23:56,303:INFO:create_model() successfully completed......................................
2024-02-06 19:23:56,507:INFO:SubProcess create_model() end ==================================
2024-02-06 19:23:56,507:INFO:Creating metrics dataframe
2024-02-06 19:23:56,525:INFO:Initializing Naive Bayes
2024-02-06 19:23:56,525:INFO:Total runtime is 0.28184943199157714 minutes
2024-02-06 19:23:56,530:INFO:SubProcess create_model() called ==================================
2024-02-06 19:23:56,531:INFO:Initializing create_model()
2024-02-06 19:23:56,531:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=nb, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:23:56,531:INFO:Checking exceptions
2024-02-06 19:23:56,531:INFO:Importing libraries
2024-02-06 19:23:56,531:INFO:Copying training dataset
2024-02-06 19:23:56,560:INFO:Defining folds
2024-02-06 19:23:56,561:INFO:Declaring metric variables
2024-02-06 19:23:56,567:INFO:Importing untrained model
2024-02-06 19:23:56,573:INFO:Naive Bayes Imported successfully
2024-02-06 19:23:56,585:INFO:Starting cross validation
2024-02-06 19:23:56,587:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:23:57,029:INFO:Calculating mean and std
2024-02-06 19:23:57,030:INFO:Creating metrics dataframe
2024-02-06 19:23:57,034:INFO:Uploading results into container
2024-02-06 19:23:57,035:INFO:Uploading model into container now
2024-02-06 19:23:57,036:INFO:_master_model_container: 23
2024-02-06 19:23:57,036:INFO:_display_container: 9
2024-02-06 19:23:57,037:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2024-02-06 19:23:57,037:INFO:create_model() successfully completed......................................
2024-02-06 19:23:57,229:INFO:SubProcess create_model() end ==================================
2024-02-06 19:23:57,231:INFO:Creating metrics dataframe
2024-02-06 19:23:57,250:INFO:Initializing Decision Tree Classifier
2024-02-06 19:23:57,250:INFO:Total runtime is 0.2939368009567261 minutes
2024-02-06 19:23:57,256:INFO:SubProcess create_model() called ==================================
2024-02-06 19:23:57,256:INFO:Initializing create_model()
2024-02-06 19:23:57,257:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=dt, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:23:57,257:INFO:Checking exceptions
2024-02-06 19:23:57,257:INFO:Importing libraries
2024-02-06 19:23:57,257:INFO:Copying training dataset
2024-02-06 19:23:57,284:INFO:Defining folds
2024-02-06 19:23:57,285:INFO:Declaring metric variables
2024-02-06 19:23:57,291:INFO:Importing untrained model
2024-02-06 19:23:57,297:INFO:Decision Tree Classifier Imported successfully
2024-02-06 19:23:57,339:INFO:Starting cross validation
2024-02-06 19:23:57,341:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:23:59,053:INFO:Calculating mean and std
2024-02-06 19:23:59,056:INFO:Creating metrics dataframe
2024-02-06 19:23:59,060:INFO:Uploading results into container
2024-02-06 19:23:59,062:INFO:Uploading model into container now
2024-02-06 19:23:59,063:INFO:_master_model_container: 24
2024-02-06 19:23:59,063:INFO:_display_container: 9
2024-02-06 19:23:59,064:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=42, splitter='best')
2024-02-06 19:23:59,064:INFO:create_model() successfully completed......................................
2024-02-06 19:23:59,275:INFO:SubProcess create_model() end ==================================
2024-02-06 19:23:59,275:INFO:Creating metrics dataframe
2024-02-06 19:23:59,294:INFO:Initializing SVM - Linear Kernel
2024-02-06 19:23:59,294:INFO:Total runtime is 0.3280047376950582 minutes
2024-02-06 19:23:59,301:INFO:SubProcess create_model() called ==================================
2024-02-06 19:23:59,301:INFO:Initializing create_model()
2024-02-06 19:23:59,301:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=svm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:23:59,302:INFO:Checking exceptions
2024-02-06 19:23:59,302:INFO:Importing libraries
2024-02-06 19:23:59,302:INFO:Copying training dataset
2024-02-06 19:23:59,332:INFO:Defining folds
2024-02-06 19:23:59,332:INFO:Declaring metric variables
2024-02-06 19:23:59,338:INFO:Importing untrained model
2024-02-06 19:23:59,344:INFO:SVM - Linear Kernel Imported successfully
2024-02-06 19:23:59,354:INFO:Starting cross validation
2024-02-06 19:23:59,356:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:24:00,007:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-06 19:24:00,007:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-06 19:24:00,081:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-06 19:24:00,116:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-06 19:24:00,157:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/utils/_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2024-02-06 19:24:00,279:INFO:Calculating mean and std
2024-02-06 19:24:00,281:INFO:Creating metrics dataframe
2024-02-06 19:24:00,285:INFO:Uploading results into container
2024-02-06 19:24:00,286:INFO:Uploading model into container now
2024-02-06 19:24:00,287:INFO:_master_model_container: 25
2024-02-06 19:24:00,287:INFO:_display_container: 9
2024-02-06 19:24:00,287:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=42, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2024-02-06 19:24:00,287:INFO:create_model() successfully completed......................................
2024-02-06 19:24:00,442:INFO:SubProcess create_model() end ==================================
2024-02-06 19:24:00,443:INFO:Creating metrics dataframe
2024-02-06 19:24:00,454:INFO:Initializing Ridge Classifier
2024-02-06 19:24:00,454:INFO:Total runtime is 0.34734456539154057 minutes
2024-02-06 19:24:00,458:INFO:SubProcess create_model() called ==================================
2024-02-06 19:24:00,458:INFO:Initializing create_model()
2024-02-06 19:24:00,458:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=ridge, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:24:00,458:INFO:Checking exceptions
2024-02-06 19:24:00,458:INFO:Importing libraries
2024-02-06 19:24:00,458:INFO:Copying training dataset
2024-02-06 19:24:00,479:INFO:Defining folds
2024-02-06 19:24:00,479:INFO:Declaring metric variables
2024-02-06 19:24:00,483:INFO:Importing untrained model
2024-02-06 19:24:00,488:INFO:Ridge Classifier Imported successfully
2024-02-06 19:24:00,497:INFO:Starting cross validation
2024-02-06 19:24:00,498:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:24:00,584:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=5.42016e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-06 19:24:00,592:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=5.21184e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-06 19:24:00,600:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.82418e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-06 19:24:00,604:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-06 19:24:00,607:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-06 19:24:00,608:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=6.2473e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-06 19:24:00,616:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-06 19:24:00,623:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-06 19:24:00,627:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/linear_model/_ridge.py:216: LinAlgWarning: Ill-conditioned matrix (rcond=4.81825e-09): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

2024-02-06 19:24:00,642:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py:190: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/metrics.py", line 182, in _score
    return super()._score(
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 127, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2024-02-06 19:24:00,767:INFO:Calculating mean and std
2024-02-06 19:24:00,769:INFO:Creating metrics dataframe
2024-02-06 19:24:00,773:INFO:Uploading results into container
2024-02-06 19:24:00,775:INFO:Uploading model into container now
2024-02-06 19:24:00,775:INFO:_master_model_container: 26
2024-02-06 19:24:00,776:INFO:_display_container: 9
2024-02-06 19:24:00,776:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=42, solver='auto',
                tol=0.0001)
2024-02-06 19:24:00,776:INFO:create_model() successfully completed......................................
2024-02-06 19:24:00,976:INFO:SubProcess create_model() end ==================================
2024-02-06 19:24:00,976:INFO:Creating metrics dataframe
2024-02-06 19:24:00,999:INFO:Initializing Random Forest Classifier
2024-02-06 19:24:00,999:INFO:Total runtime is 0.35642603635787967 minutes
2024-02-06 19:24:01,005:INFO:SubProcess create_model() called ==================================
2024-02-06 19:24:01,006:INFO:Initializing create_model()
2024-02-06 19:24:01,006:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=rf, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:24:01,006:INFO:Checking exceptions
2024-02-06 19:24:01,006:INFO:Importing libraries
2024-02-06 19:24:01,006:INFO:Copying training dataset
2024-02-06 19:24:01,033:INFO:Defining folds
2024-02-06 19:24:01,033:INFO:Declaring metric variables
2024-02-06 19:24:01,039:INFO:Importing untrained model
2024-02-06 19:24:01,047:INFO:Random Forest Classifier Imported successfully
2024-02-06 19:24:01,060:INFO:Starting cross validation
2024-02-06 19:24:01,062:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:24:13,012:INFO:Calculating mean and std
2024-02-06 19:24:13,014:INFO:Creating metrics dataframe
2024-02-06 19:24:13,019:INFO:Uploading results into container
2024-02-06 19:24:13,019:INFO:Uploading model into container now
2024-02-06 19:24:13,020:INFO:_master_model_container: 27
2024-02-06 19:24:13,020:INFO:_display_container: 9
2024-02-06 19:24:13,021:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False)
2024-02-06 19:24:13,021:INFO:create_model() successfully completed......................................
2024-02-06 19:24:13,211:INFO:SubProcess create_model() end ==================================
2024-02-06 19:24:13,211:INFO:Creating metrics dataframe
2024-02-06 19:24:13,232:INFO:Initializing Quadratic Discriminant Analysis
2024-02-06 19:24:13,232:INFO:Total runtime is 0.5602988163630168 minutes
2024-02-06 19:24:13,237:INFO:SubProcess create_model() called ==================================
2024-02-06 19:24:13,238:INFO:Initializing create_model()
2024-02-06 19:24:13,238:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=qda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:24:13,238:INFO:Checking exceptions
2024-02-06 19:24:13,239:INFO:Importing libraries
2024-02-06 19:24:13,239:INFO:Copying training dataset
2024-02-06 19:24:13,266:INFO:Defining folds
2024-02-06 19:24:13,266:INFO:Declaring metric variables
2024-02-06 19:24:13,273:INFO:Importing untrained model
2024-02-06 19:24:13,282:INFO:Quadratic Discriminant Analysis Imported successfully
2024-02-06 19:24:13,293:INFO:Starting cross validation
2024-02-06 19:24:13,295:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:24:13,782:INFO:Calculating mean and std
2024-02-06 19:24:13,783:INFO:Creating metrics dataframe
2024-02-06 19:24:13,788:INFO:Uploading results into container
2024-02-06 19:24:13,789:INFO:Uploading model into container now
2024-02-06 19:24:13,789:INFO:_master_model_container: 28
2024-02-06 19:24:13,789:INFO:_display_container: 9
2024-02-06 19:24:13,789:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2024-02-06 19:24:13,790:INFO:create_model() successfully completed......................................
2024-02-06 19:24:13,976:INFO:SubProcess create_model() end ==================================
2024-02-06 19:24:13,977:INFO:Creating metrics dataframe
2024-02-06 19:24:14,003:INFO:Initializing Ada Boost Classifier
2024-02-06 19:24:14,004:INFO:Total runtime is 0.5731618841489157 minutes
2024-02-06 19:24:14,010:INFO:SubProcess create_model() called ==================================
2024-02-06 19:24:14,011:INFO:Initializing create_model()
2024-02-06 19:24:14,012:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=ada, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:24:14,012:INFO:Checking exceptions
2024-02-06 19:24:14,012:INFO:Importing libraries
2024-02-06 19:24:14,012:INFO:Copying training dataset
2024-02-06 19:24:14,038:INFO:Defining folds
2024-02-06 19:24:14,038:INFO:Declaring metric variables
2024-02-06 19:24:14,043:INFO:Importing untrained model
2024-02-06 19:24:14,048:INFO:Ada Boost Classifier Imported successfully
2024-02-06 19:24:14,060:INFO:Starting cross validation
2024-02-06 19:24:14,062:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:24:20,111:INFO:Calculating mean and std
2024-02-06 19:24:20,113:INFO:Creating metrics dataframe
2024-02-06 19:24:20,118:INFO:Uploading results into container
2024-02-06 19:24:20,118:INFO:Uploading model into container now
2024-02-06 19:24:20,119:INFO:_master_model_container: 29
2024-02-06 19:24:20,119:INFO:_display_container: 9
2024-02-06 19:24:20,120:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=42)
2024-02-06 19:24:20,120:INFO:create_model() successfully completed......................................
2024-02-06 19:24:20,305:INFO:SubProcess create_model() end ==================================
2024-02-06 19:24:20,305:INFO:Creating metrics dataframe
2024-02-06 19:24:20,327:INFO:Initializing Gradient Boosting Classifier
2024-02-06 19:24:20,328:INFO:Total runtime is 0.6785647988319398 minutes
2024-02-06 19:24:20,333:INFO:SubProcess create_model() called ==================================
2024-02-06 19:24:20,334:INFO:Initializing create_model()
2024-02-06 19:24:20,334:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=gbc, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:24:20,334:INFO:Checking exceptions
2024-02-06 19:24:20,334:INFO:Importing libraries
2024-02-06 19:24:20,334:INFO:Copying training dataset
2024-02-06 19:24:20,359:INFO:Defining folds
2024-02-06 19:24:20,359:INFO:Declaring metric variables
2024-02-06 19:24:20,364:INFO:Importing untrained model
2024-02-06 19:24:20,368:INFO:Gradient Boosting Classifier Imported successfully
2024-02-06 19:24:20,378:INFO:Starting cross validation
2024-02-06 19:24:20,379:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:24:47,572:INFO:Calculating mean and std
2024-02-06 19:24:47,574:INFO:Creating metrics dataframe
2024-02-06 19:24:47,578:INFO:Uploading results into container
2024-02-06 19:24:47,578:INFO:Uploading model into container now
2024-02-06 19:24:47,579:INFO:_master_model_container: 30
2024-02-06 19:24:47,579:INFO:_display_container: 9
2024-02-06 19:24:47,580:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2024-02-06 19:24:47,580:INFO:create_model() successfully completed......................................
2024-02-06 19:24:47,734:INFO:SubProcess create_model() end ==================================
2024-02-06 19:24:47,734:INFO:Creating metrics dataframe
2024-02-06 19:24:47,747:INFO:Initializing Linear Discriminant Analysis
2024-02-06 19:24:47,747:INFO:Total runtime is 1.1355531533559164 minutes
2024-02-06 19:24:47,751:INFO:SubProcess create_model() called ==================================
2024-02-06 19:24:47,751:INFO:Initializing create_model()
2024-02-06 19:24:47,751:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=lda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:24:47,751:INFO:Checking exceptions
2024-02-06 19:24:47,751:INFO:Importing libraries
2024-02-06 19:24:47,751:INFO:Copying training dataset
2024-02-06 19:24:47,771:INFO:Defining folds
2024-02-06 19:24:47,771:INFO:Declaring metric variables
2024-02-06 19:24:47,775:INFO:Importing untrained model
2024-02-06 19:24:47,780:INFO:Linear Discriminant Analysis Imported successfully
2024-02-06 19:24:47,788:INFO:Starting cross validation
2024-02-06 19:24:47,790:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:24:48,376:INFO:Calculating mean and std
2024-02-06 19:24:48,378:INFO:Creating metrics dataframe
2024-02-06 19:24:48,382:INFO:Uploading results into container
2024-02-06 19:24:48,383:INFO:Uploading model into container now
2024-02-06 19:24:48,384:INFO:_master_model_container: 31
2024-02-06 19:24:48,384:INFO:_display_container: 9
2024-02-06 19:24:48,384:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2024-02-06 19:24:48,384:INFO:create_model() successfully completed......................................
2024-02-06 19:24:48,536:INFO:SubProcess create_model() end ==================================
2024-02-06 19:24:48,536:INFO:Creating metrics dataframe
2024-02-06 19:24:48,548:INFO:Initializing Extra Trees Classifier
2024-02-06 19:24:48,549:INFO:Total runtime is 1.1489155332247418 minutes
2024-02-06 19:24:48,553:INFO:SubProcess create_model() called ==================================
2024-02-06 19:24:48,553:INFO:Initializing create_model()
2024-02-06 19:24:48,553:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=et, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:24:48,553:INFO:Checking exceptions
2024-02-06 19:24:48,553:INFO:Importing libraries
2024-02-06 19:24:48,553:INFO:Copying training dataset
2024-02-06 19:24:48,575:INFO:Defining folds
2024-02-06 19:24:48,575:INFO:Declaring metric variables
2024-02-06 19:24:48,578:INFO:Importing untrained model
2024-02-06 19:24:48,582:INFO:Extra Trees Classifier Imported successfully
2024-02-06 19:24:48,590:INFO:Starting cross validation
2024-02-06 19:24:48,591:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:24:52,037:INFO:Calculating mean and std
2024-02-06 19:24:52,038:INFO:Creating metrics dataframe
2024-02-06 19:24:52,042:INFO:Uploading results into container
2024-02-06 19:24:52,043:INFO:Uploading model into container now
2024-02-06 19:24:52,043:INFO:_master_model_container: 32
2024-02-06 19:24:52,043:INFO:_display_container: 9
2024-02-06 19:24:52,044:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=42, verbose=0, warm_start=False)
2024-02-06 19:24:52,044:INFO:create_model() successfully completed......................................
2024-02-06 19:24:52,197:INFO:SubProcess create_model() end ==================================
2024-02-06 19:24:52,197:INFO:Creating metrics dataframe
2024-02-06 19:24:52,211:INFO:Initializing Light Gradient Boosting Machine
2024-02-06 19:24:52,212:INFO:Total runtime is 1.2099637667338055 minutes
2024-02-06 19:24:52,215:INFO:SubProcess create_model() called ==================================
2024-02-06 19:24:52,216:INFO:Initializing create_model()
2024-02-06 19:24:52,216:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=lightgbm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:24:52,216:INFO:Checking exceptions
2024-02-06 19:24:52,216:INFO:Importing libraries
2024-02-06 19:24:52,216:INFO:Copying training dataset
2024-02-06 19:24:52,236:INFO:Defining folds
2024-02-06 19:24:52,237:INFO:Declaring metric variables
2024-02-06 19:24:52,241:INFO:Importing untrained model
2024-02-06 19:24:52,245:INFO:Light Gradient Boosting Machine Imported successfully
2024-02-06 19:24:52,253:INFO:Starting cross validation
2024-02-06 19:24:52,254:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:24:57,586:INFO:Calculating mean and std
2024-02-06 19:24:57,588:INFO:Creating metrics dataframe
2024-02-06 19:24:57,592:INFO:Uploading results into container
2024-02-06 19:24:57,593:INFO:Uploading model into container now
2024-02-06 19:24:57,594:INFO:_master_model_container: 33
2024-02-06 19:24:57,594:INFO:_display_container: 9
2024-02-06 19:24:57,595:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2024-02-06 19:24:57,595:INFO:create_model() successfully completed......................................
2024-02-06 19:24:57,767:INFO:SubProcess create_model() end ==================================
2024-02-06 19:24:57,768:INFO:Creating metrics dataframe
2024-02-06 19:24:57,780:INFO:Initializing Dummy Classifier
2024-02-06 19:24:57,780:INFO:Total runtime is 1.302772037188212 minutes
2024-02-06 19:24:57,784:INFO:SubProcess create_model() called ==================================
2024-02-06 19:24:57,784:INFO:Initializing create_model()
2024-02-06 19:24:57,785:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=dummy, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fee0621bfa0>, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:24:57,785:INFO:Checking exceptions
2024-02-06 19:24:57,785:INFO:Importing libraries
2024-02-06 19:24:57,785:INFO:Copying training dataset
2024-02-06 19:24:57,806:INFO:Defining folds
2024-02-06 19:24:57,806:INFO:Declaring metric variables
2024-02-06 19:24:57,810:INFO:Importing untrained model
2024-02-06 19:24:57,814:INFO:Dummy Classifier Imported successfully
2024-02-06 19:24:57,824:INFO:Starting cross validation
2024-02-06 19:24:57,825:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:24:57,942:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-06 19:24:57,942:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-06 19:24:57,942:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-06 19:24:57,954:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-06 19:24:57,958:WARNING:/Applications/anaconda3/envs/consta_ml/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2024-02-06 19:24:58,076:INFO:Calculating mean and std
2024-02-06 19:24:58,077:INFO:Creating metrics dataframe
2024-02-06 19:24:58,082:INFO:Uploading results into container
2024-02-06 19:24:58,083:INFO:Uploading model into container now
2024-02-06 19:24:58,083:INFO:_master_model_container: 34
2024-02-06 19:24:58,084:INFO:_display_container: 9
2024-02-06 19:24:58,084:INFO:DummyClassifier(constant=None, random_state=42, strategy='prior')
2024-02-06 19:24:58,084:INFO:create_model() successfully completed......................................
2024-02-06 19:24:58,267:INFO:SubProcess create_model() end ==================================
2024-02-06 19:24:58,267:INFO:Creating metrics dataframe
2024-02-06 19:24:58,305:INFO:Initializing create_model()
2024-02-06 19:24:58,306:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0), fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:24:58,306:INFO:Checking exceptions
2024-02-06 19:24:58,309:INFO:Importing libraries
2024-02-06 19:24:58,310:INFO:Copying training dataset
2024-02-06 19:24:58,333:INFO:Defining folds
2024-02-06 19:24:58,334:INFO:Declaring metric variables
2024-02-06 19:24:58,334:INFO:Importing untrained model
2024-02-06 19:24:58,334:INFO:Declaring custom model
2024-02-06 19:24:58,335:INFO:Light Gradient Boosting Machine Imported successfully
2024-02-06 19:24:58,336:INFO:Cross validation set to False
2024-02-06 19:24:58,336:INFO:Fitting Model
2024-02-06 19:24:58,439:INFO:[LightGBM] [Info] Number of positive: 7596, number of negative: 31211
2024-02-06 19:24:58,444:INFO:[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003543 seconds.
2024-02-06 19:24:58,444:INFO:You can set `force_col_wise=true` to remove the overhead.
2024-02-06 19:24:58,444:INFO:[LightGBM] [Info] Total Bins 6054
2024-02-06 19:24:58,445:INFO:[LightGBM] [Info] Number of data points in the train set: 38807, number of used features: 24
2024-02-06 19:24:58,446:INFO:[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.195738 -> initscore=-1.413149
2024-02-06 19:24:58,446:INFO:[LightGBM] [Info] Start training from score -1.413149
2024-02-06 19:24:58,737:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2024-02-06 19:24:58,737:INFO:create_model() successfully completed......................................
2024-02-06 19:24:58,937:INFO:Initializing create_model()
2024-02-06 19:24:58,937:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=42, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:24:58,938:INFO:Checking exceptions
2024-02-06 19:24:58,941:INFO:Importing libraries
2024-02-06 19:24:58,941:INFO:Copying training dataset
2024-02-06 19:24:58,962:INFO:Defining folds
2024-02-06 19:24:58,963:INFO:Declaring metric variables
2024-02-06 19:24:58,963:INFO:Importing untrained model
2024-02-06 19:24:58,963:INFO:Declaring custom model
2024-02-06 19:24:58,965:INFO:Extra Trees Classifier Imported successfully
2024-02-06 19:24:58,966:INFO:Cross validation set to False
2024-02-06 19:24:58,966:INFO:Fitting Model
2024-02-06 19:24:59,696:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=42, verbose=0, warm_start=False)
2024-02-06 19:24:59,696:INFO:create_model() successfully completed......................................
2024-02-06 19:24:59,890:INFO:Initializing create_model()
2024-02-06 19:24:59,890:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:24:59,890:INFO:Checking exceptions
2024-02-06 19:24:59,893:INFO:Importing libraries
2024-02-06 19:24:59,893:INFO:Copying training dataset
2024-02-06 19:24:59,919:INFO:Defining folds
2024-02-06 19:24:59,919:INFO:Declaring metric variables
2024-02-06 19:24:59,919:INFO:Importing untrained model
2024-02-06 19:24:59,920:INFO:Declaring custom model
2024-02-06 19:24:59,920:INFO:Random Forest Classifier Imported successfully
2024-02-06 19:24:59,922:INFO:Cross validation set to False
2024-02-06 19:24:59,922:INFO:Fitting Model
2024-02-06 19:25:02,981:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False)
2024-02-06 19:25:02,981:INFO:create_model() successfully completed......................................
2024-02-06 19:25:03,207:INFO:_master_model_container: 34
2024-02-06 19:25:03,208:INFO:_display_container: 9
2024-02-06 19:25:03,209:INFO:[LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=42, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0), ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=42, verbose=0, warm_start=False), RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False)]
2024-02-06 19:25:03,209:INFO:compare_models() successfully completed......................................
2024-02-06 19:27:02,798:INFO:Initializing tune_model()
2024-02-06 19:27:02,799:INFO:tune_model(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False), fold=5, round=4, n_iter=10, custom_grid=None, optimize=F1, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=True, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, return_train_score=False, kwargs={}, self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>)
2024-02-06 19:27:02,799:INFO:Checking exceptions
2024-02-06 19:27:02,846:INFO:Copying training dataset
2024-02-06 19:27:02,869:INFO:Checking base model
2024-02-06 19:27:02,869:INFO:Base model : Random Forest Classifier
2024-02-06 19:27:02,878:INFO:Declaring metric variables
2024-02-06 19:27:02,888:INFO:Defining Hyperparameters
2024-02-06 19:27:03,206:INFO:Tuning with n_jobs=-1
2024-02-06 19:27:03,206:INFO:Initializing RandomizedSearchCV
2024-02-06 19:29:15,152:INFO:best_params: {'actual_estimator__n_estimators': 120, 'actual_estimator__min_samples_split': 5, 'actual_estimator__min_samples_leaf': 6, 'actual_estimator__min_impurity_decrease': 0, 'actual_estimator__max_features': 'sqrt', 'actual_estimator__max_depth': 9, 'actual_estimator__criterion': 'gini', 'actual_estimator__class_weight': {}, 'actual_estimator__bootstrap': True}
2024-02-06 19:29:15,153:INFO:Hyperparameter search completed
2024-02-06 19:29:15,153:INFO:SubProcess create_model() called ==================================
2024-02-06 19:29:15,154:INFO:Initializing create_model()
2024-02-06 19:29:15,154:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=True, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x7fedfcca3940>, model_only=True, return_train_score=False, error_score=0.0, kwargs={'n_estimators': 120, 'min_samples_split': 5, 'min_samples_leaf': 6, 'min_impurity_decrease': 0, 'max_features': 'sqrt', 'max_depth': 9, 'criterion': 'gini', 'class_weight': {}, 'bootstrap': True})
2024-02-06 19:29:15,154:INFO:Checking exceptions
2024-02-06 19:29:15,154:INFO:Importing libraries
2024-02-06 19:29:15,154:INFO:Copying training dataset
2024-02-06 19:29:15,179:INFO:Defining folds
2024-02-06 19:29:15,179:INFO:Declaring metric variables
2024-02-06 19:29:15,183:INFO:Importing untrained model
2024-02-06 19:29:15,184:INFO:Declaring custom model
2024-02-06 19:29:15,189:INFO:Random Forest Classifier Imported successfully
2024-02-06 19:29:15,199:INFO:Starting cross validation
2024-02-06 19:29:15,200:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:29:26,137:INFO:Calculating mean and std
2024-02-06 19:29:26,139:INFO:Creating metrics dataframe
2024-02-06 19:29:26,148:INFO:Finalizing model
2024-02-06 19:29:28,966:INFO:Uploading results into container
2024-02-06 19:29:28,967:INFO:Uploading model into container now
2024-02-06 19:29:28,968:INFO:_master_model_container: 35
2024-02-06 19:29:28,968:INFO:_display_container: 10
2024-02-06 19:29:28,969:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight={},
                       criterion='gini', max_depth=9, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0, min_samples_leaf=6,
                       min_samples_split=5, min_weight_fraction_leaf=0.0,
                       n_estimators=120, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False)
2024-02-06 19:29:28,970:INFO:create_model() successfully completed......................................
2024-02-06 19:29:29,143:INFO:SubProcess create_model() end ==================================
2024-02-06 19:29:29,144:INFO:choose_better activated
2024-02-06 19:29:29,150:INFO:SubProcess create_model() called ==================================
2024-02-06 19:29:29,151:INFO:Initializing create_model()
2024-02-06 19:29:29,151:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x7fee09aa7880>, estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2024-02-06 19:29:29,152:INFO:Checking exceptions
2024-02-06 19:29:29,154:INFO:Importing libraries
2024-02-06 19:29:29,154:INFO:Copying training dataset
2024-02-06 19:29:29,178:INFO:Defining folds
2024-02-06 19:29:29,178:INFO:Declaring metric variables
2024-02-06 19:29:29,178:INFO:Importing untrained model
2024-02-06 19:29:29,178:INFO:Declaring custom model
2024-02-06 19:29:29,179:INFO:Random Forest Classifier Imported successfully
2024-02-06 19:29:29,180:INFO:Starting cross validation
2024-02-06 19:29:29,181:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2024-02-06 19:29:39,970:INFO:Calculating mean and std
2024-02-06 19:29:39,971:INFO:Creating metrics dataframe
2024-02-06 19:29:39,973:INFO:Finalizing model
2024-02-06 19:29:42,869:INFO:Uploading results into container
2024-02-06 19:29:42,870:INFO:Uploading model into container now
2024-02-06 19:29:42,870:INFO:_master_model_container: 36
2024-02-06 19:29:42,871:INFO:_display_container: 11
2024-02-06 19:29:42,871:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False)
2024-02-06 19:29:42,871:INFO:create_model() successfully completed......................................
2024-02-06 19:29:43,050:INFO:SubProcess create_model() end ==================================
2024-02-06 19:29:43,051:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False) result for F1 is 0.9757
2024-02-06 19:29:43,052:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight={},
                       criterion='gini', max_depth=9, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0, min_samples_leaf=6,
                       min_samples_split=5, min_weight_fraction_leaf=0.0,
                       n_estimators=120, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False) result for F1 is 0.9594
2024-02-06 19:29:43,053:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False) is best model
2024-02-06 19:29:43,053:INFO:choose_better completed
2024-02-06 19:29:43,053:INFO:Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).
2024-02-06 19:29:43,069:INFO:_master_model_container: 36
2024-02-06 19:29:43,070:INFO:_display_container: 10
2024-02-06 19:29:43,070:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=42, verbose=0, warm_start=False)
2024-02-06 19:29:43,070:INFO:tune_model() successfully completed......................................
